server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Habilita compressão gGzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Rotas base (Landing Page)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Rotas do WebApp (SPA) - Ficam sob responsabilidade do /src/index.html
    location /dashboard { try_files $uri $uri/ /src/index.html; }
    location /prazos { try_files $uri $uri/ /src/index.html; }
    location /processos { try_files $uri $uri/ /src/index.html; }
    location /processo { try_files $uri $uri/ /src/index.html; }
    location /clientes { try_files $uri $uri/ /src/index.html; }
    location /crm { try_files $uri $uri/ /src/index.html; }
    location /config { try_files $uri $uri/ /src/index.html; }

    # Rota específica de assets e scripts dentro de /src/
    location /src/ {
        try_files $uri $uri/ /src/index.html;
    }

    # Permitir que as páginas e scripts carreguem sem problemas de cache durante DEV
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
